version: '3.7'
services:
  vscode:
    image: codercom/code-server
    container_name: vscode
    user: root
    restart: always
    volumes:
      - ./:/home/coder/project
      - ./.local:/home/coder/.local/share/code-server
    ports:
      - 8080:8080
